### ISSUE TITLE
Recursive option doesn't work

### ISSUE THREAD

**Issue by iainmwallace** [ciakovx/rorcid.workshop#3]
Hi,

I am noticing that the recursive option in the orcid function doesn't appear to do anything
i.e. 
orcid(query="Bristol Myers Squibb",recursive = TRUE) will return 100 rows
while 
orcid(query="Bristol Myers Squibb",rows=200) will return 200 rows

thanks

Iain

**Comment by iainmwallace** [comment]
Sorry wrong repo

**Comment by ciakovx** [comment]
Hi  iain,

Yeah I noticed that too and saw you opened an issue. You may have noticed how I got around it, by calling `my_osu_orcid_count <- base::attr(rorcid::orcid(query = YOUR QUERY HERE"'),
                      "found")`
Then creating a page vector `my_pages <- seq(from = 0, to = my_osu_orcid_count, by = 200)`

And then calling `map` on that vector; it's detailed under https://ciakovx.github.io/rorcid.html#searching_with_boolean_or.

I'm happy to hear any other bugs you may have come across in that walkthrough.
